/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPage.java
 *
 * Created on Mar 23, 2011, 10:48:17 AM
 */
package com.wordpress.salaboy.content.ui;

import com.wordpress.salaboy.content.model.VisualComponent;
import com.wordpress.salaboy.content.model.components.SwingVisualComponent;
import com.wordpress.salaboy.content.model.events.BuyProductEvent;
import com.wordpress.salaboy.content.model.events.ProductFocusGainedEvent;
import com.wordpress.salaboy.content.model.events.ProductFocusLostEvent;
import com.wordpress.salaboy.content.model.meta.Product;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import org.drools.KnowledgeBase;
import org.drools.KnowledgeBaseConfiguration;
import org.drools.KnowledgeBaseFactory;
import org.drools.builder.KnowledgeBuilder;
import org.drools.builder.KnowledgeBuilderError;
import org.drools.builder.KnowledgeBuilderErrors;
import org.drools.builder.KnowledgeBuilderFactory;
import org.drools.builder.ResourceType;
import org.drools.conf.EventProcessingOption;
import org.drools.definition.rule.Rule;
import org.drools.event.rule.DebugAgendaEventListener;
import org.drools.io.impl.ByteArrayResource;
import org.drools.io.impl.ClassPathResource;
import org.drools.logger.KnowledgeRuntimeLoggerFactory;
import org.drools.runtime.KnowledgeSessionConfiguration;
import org.drools.runtime.StatefulKnowledgeSession;
import org.drools.runtime.conf.ClockTypeOption;

/**
 *
 * @author salaboy
 */
public class MainPage extends javax.swing.JDialog {

    private StatefulKnowledgeSession ksession = null;

    /** Creates new form MainPage */
    public MainPage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        instantiateSwingComponents();
        loadRulesFromFile();
        initDrools();
        myInitComponents();
        updateCurrentVisualStatus();
       

    }

    public final void initDrools() {
        // Create the Knowledge Builder
        KnowledgeBuilder kbuilder = KnowledgeBuilderFactory.newKnowledgeBuilder();
        // Add our rules
        //kbuilder.add(new ClassPathResource("event-rules.drl"), ResourceType.DRL);
        kbuilder.add(new ClassPathResource("event-rules.dsl"), ResourceType.DSL);
        kbuilder.add(new ByteArrayResource(jTextArea2.getText().getBytes()), ResourceType.DSLR);
        //Check for errors during the compilation of the rules
        KnowledgeBuilderErrors errors = kbuilder.getErrors();
        if (errors.size() > 0) {
            for (KnowledgeBuilderError error : errors) {
                System.err.println(error);
            }
            throw new IllegalArgumentException("Could not parse knowledge.");
        }

        KnowledgeBaseConfiguration config = KnowledgeBaseFactory.newKnowledgeBaseConfiguration();
        config.setOption(EventProcessingOption.STREAM);

        // Create the Knowledge Base
        KnowledgeBase kbase = KnowledgeBaseFactory.newKnowledgeBase(config);

        // Add the binary packages (compiled rules) to the Knowledge Base
        kbase.addKnowledgePackages(kbuilder.getKnowledgePackages());
        // Create the StatefulSession using the Knowledge Base that contains
        // the compiled rules   
        String deployedRules = "";
        for(Rule rule : kbase.getKnowledgePackages().iterator().next().getRules()){
            deployedRules += " - " + rule.getName() + "\n";
        }
        jTextArea1.setText(jTextArea1.getText() + "\n Deployed Rules: "+ deployedRules);
        KnowledgeSessionConfiguration kconfig = KnowledgeBaseFactory.newKnowledgeSessionConfiguration();
        kconfig.setOption(ClockTypeOption.get("realtime"));
        jTextArea1.setText(jTextArea1.getText() + "\n New Session Was Created!");
        ksession = kbase.newStatefulKnowledgeSession(kconfig, null);

        // We can add a runtime logger to understand what is going on inside the
        // Engine
        KnowledgeRuntimeLoggerFactory.newConsoleLogger(ksession);
        ksession.addEventListener(new DebugAgendaEventListener());
        ksession.setGlobal("notifications", jTextArea1);
        ksession.setGlobal("panel", jDesktopPane1);
        new Thread() {

            @Override
            public void run() {
                ksession.fireUntilHalt();
            }
        }.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jInternalFrame7 = new javax.swing.JInternalFrame();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jInternalFrame8 = new javax.swing.JInternalFrame();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRuleHeader = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Notifications:");

        jTabbedPane3.setName("Management Tab"); // NOI18N

        jDesktopPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MainPage.this.focusGained(evt);
            }
        });

        jInternalFrame6.setClosable(true);
        jInternalFrame6.setIconifiable(true);
        jInternalFrame6.setMaximizable(true);
        jInternalFrame6.setResizable(true);
        jInternalFrame6.setVisible(true);
        jInternalFrame6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jInternalFrame6FocusLost(evt);
            }
        });

        jButton1.setText("Buy Product 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add Banner");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("Add Component");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jInternalFrame6Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame6.getContentPane());
        jInternalFrame6.getContentPane().setLayout(jInternalFrame6Layout);
        jInternalFrame6Layout.setHorizontalGroup(
            jInternalFrame6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(jButton2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jInternalFrame6Layout.createSequentialGroup()
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 52, Short.MAX_VALUE)
                        .add(jButton7)))
                .addContainerGap())
        );
        jInternalFrame6Layout.setVerticalGroup(
            jInternalFrame6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame6Layout.createSequentialGroup()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jInternalFrame6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton7)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jInternalFrame6.setBounds(310, 200, 300, 151);
        jDesktopPane1.add(jInternalFrame6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame7.setClosable(true);
        jInternalFrame7.setIconifiable(true);
        jInternalFrame7.setMaximizable(true);
        jInternalFrame7.setResizable(true);
        jInternalFrame7.setTitle("Lifestyle");
        jInternalFrame7.setVisible(true);

        jCheckBox1.setText("Entertainment");

        jCheckBox2.setText("Social");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Business");

        jCheckBox4.setText("Classic");

        jButton3.setText("Apply");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jInternalFrame7Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame7.getContentPane());
        jInternalFrame7.getContentPane().setLayout(jInternalFrame7Layout);
        jInternalFrame7Layout.setHorizontalGroup(
            jInternalFrame7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jInternalFrame7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBox2)
                    .add(jCheckBox3)
                    .add(jCheckBox4)
                    .add(jButton3)
                    .add(jCheckBox1))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jInternalFrame7Layout.setVerticalGroup(
            jInternalFrame7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame7Layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(jCheckBox2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBox1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBox3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBox4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 6, Short.MAX_VALUE)
                .add(jButton3))
        );

        jInternalFrame7.setBounds(650, 110, 220, 190);
        jDesktopPane1.add(jInternalFrame7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame8.setClosable(true);
        jInternalFrame8.setIconifiable(true);
        jInternalFrame8.setMaximizable(true);
        jInternalFrame8.setResizable(true);
        jInternalFrame8.setTitle("Search/Interest");
        jInternalFrame8.setVisible(true);

        jButton4.setText("Go!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jInternalFrame8Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame8.getContentPane());
        jInternalFrame8.getContentPane().setLayout(jInternalFrame8Layout);
        jInternalFrame8Layout.setHorizontalGroup(
            jInternalFrame8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jInternalFrame8Layout.createSequentialGroup()
                .addContainerGap()
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jInternalFrame8Layout.setVerticalGroup(
            jInternalFrame8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jInternalFrame8Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .add(jInternalFrame8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4))
                .addContainerGap())
        );

        jInternalFrame8.setBounds(650, 290, 220, 110);
        jDesktopPane1.add(jInternalFrame8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane3.addTab("Customer Page", jDesktopPane1);

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Apply");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jScrollPane2.setName("Header"); // NOI18N

        txtRuleHeader.setColumns(20);
        txtRuleHeader.setRows(5);
        jScrollPane2.setViewportView(txtRuleHeader);

        jTabbedPane2.addTab("Header", jScrollPane2);

        jScrollPane3.setName("Rules"); // NOI18N

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jTabbedPane2.addTab("Rules", jScrollPane3);

        jTabbedPane2.setSelectedIndex(1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton5)
                    .add(jButton6))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(224, 224, 224)
                        .add(jButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton6))
                    .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Manegement Tab", jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTabbedPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //saveRules();
        initDrools();
        updateCurrentVisualStatus();
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        loadRulesFromFile();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
        
}//GEN-LAST:event_focusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //        ksession.getWorkingMemoryEntryPoint("visit-product-stream")
        //                    .insert(new SearchTriggeredEvent(jTextField1.getText()));
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
}//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jInternalFrame6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInternalFrame6FocusLost
        // TODO add your handling code here:
}//GEN-LAST:event_jInternalFrame6FocusLost

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        SwingVisualComponent productXComponent = new SwingVisualComponent(jTextField2.getText(), 30, 230);
        visualComponents.add(productXComponent);
        JInternalFrame jInternalFrameX = productXComponent.getFrame();
        jDesktopPane1.add(jInternalFrameX, javax.swing.JLayeredPane.DEFAULT_LAYER);
        updateCurrentVisualStatus();
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jInternalFrame10 = new javax.swing.JInternalFrame();
        jLabel20 = new javax.swing.JLabel();
        jInternalFrame10.setTitle("Banner 1");
        jInternalFrame10.setVisible(true);
        jInternalFrame10.addMouseListener(new java.awt.event.MouseAdapter() {
            
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                internalFrameMouseClicked(evt);
            }
        });
        jInternalFrame10.addFocusListener(new java.awt.event.FocusAdapter() {
            
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                MainPage.this.focusGained(evt);
            }
        });
        
        jLabel20.setText("Banner \nContent");
        
        org.jdesktop.layout.GroupLayout jInternalFrame10Layout = new org.jdesktop.layout.GroupLayout(jInternalFrame10.getContentPane());
        jInternalFrame10.getContentPane().setLayout(jInternalFrame10Layout);
        jInternalFrame10Layout.setHorizontalGroup(
                jInternalFrame10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jInternalFrame10Layout.createSequentialGroup().addContainerGap().add(jLabel20).addContainerGap(136, Short.MAX_VALUE)));
        jInternalFrame10Layout.setVerticalGroup(
                jInternalFrame10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jInternalFrame10Layout.createSequentialGroup().addContainerGap().add(jLabel20).addContainerGap(28, Short.MAX_VALUE)));
        
        jInternalFrame10.setBounds(480, 10, 200, 250);
        jDesktopPane1.add(jInternalFrame10, javax.swing.JLayeredPane.DEFAULT_LAYER);
}//GEN-LAST:event_jButton2ActionPerformed

    private void internalFrameMouseClicked(java.awt.event.MouseEvent evt){
        evt.getComponent().requestFocus();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ksession.getWorkingMemoryEntryPoint("buy-product-stream").insert(new BuyProductEvent());
}//GEN-LAST:event_jButton1ActionPerformed

    public void myFocusGained(java.awt.event.FocusEvent evt) {
        if (evt.getComponent() instanceof JInternalFrame) {
            jTextArea1.setText(((JInternalFrame) evt.getComponent()).getTitle());
            ksession.getWorkingMemoryEntryPoint("visit-product-stream").insert(new ProductFocusGainedEvent(new Product(((JInternalFrame) evt.getComponent()).getTitle())));

        }

    }

    public void myFocusLost(java.awt.event.FocusEvent evt) {
        if (evt.getComponent() instanceof JInternalFrame) {
            jTextArea1.setText(((JInternalFrame) evt.getComponent()).getTitle());
            ksession.getWorkingMemoryEntryPoint("visit-product-stream").insert(new ProductFocusLostEvent(new Product(((JInternalFrame) evt.getComponent()).getTitle())));

        }

    }
    private static MainPage instance = null;

    public static MainPage getInstance() {
        if (instance == null) {
            instance = new MainPage(new javax.swing.JFrame(), true);
        }
        return instance;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MainPage dialog = MainPage.getInstance();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JInternalFrame jInternalFrame7;
    private javax.swing.JInternalFrame jInternalFrame8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea txtRuleHeader;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JInternalFrame jInternalFrame10;
    private javax.swing.JLabel jLabel20;
    private List<SwingVisualComponent> visualComponents;
    
    private void instantiateSwingComponents() {
        visualComponents = new ArrayList<SwingVisualComponent>();
    }

    private void myInitComponents() {
        SwingVisualComponent product1Component = new SwingVisualComponent("Product 1", 30, 30);
        visualComponents.add(product1Component);
        JInternalFrame internalFrame = product1Component.getFrame();
        internalFrame.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                internalFrameMouseClicked(e);
            }
            
        });
        jDesktopPane1.add(internalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);


        SwingVisualComponent product2Component = new SwingVisualComponent("Product 2", 280, 30);
        visualComponents.add(product2Component);
        internalFrame = product2Component.getFrame();
        internalFrame.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                internalFrameMouseClicked(e);
            }
            
        });
        jDesktopPane1.add(internalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);


        SwingVisualComponent product3Component = new SwingVisualComponent("Product 3", 530, 30);
        visualComponents.add(product3Component);
        internalFrame = product3Component.getFrame();
        internalFrame.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                internalFrameMouseClicked(e);
            }
            
        });
        jDesktopPane1.add(internalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        pack();
        
    }

  

    private void updateCurrentVisualStatus() {
        for(VisualComponent component : visualComponents){
            ksession.insert(component);
        }
    }

    private void loadRulesFromFile() {
        BufferedReader in = null;
        try {
            String text = "";
            in = new BufferedReader(new InputStreamReader(new ClassPathResource("event-rules.dslr").getInputStream()));
            String line = null;
            while ((line = in.readLine()) != null) {
                text += line + "\n";
            }
            jTextArea2.setText(text);
        } catch (IOException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                in.close();
            } catch (IOException ex) {
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
