/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShoppingCartFrame.java
 *
 * Created on Mar 30, 2011, 3:54:01 PM
 */

package com.wordpress.salaboy.content.ui;

import com.wordpress.salaboy.content.model.meta.Product;
import com.wordpress.salaboy.content.model.meta.ShoppingCart;
import com.wordpress.salaboy.content.model.meta.listener.ShoppingCartEventListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author esteban
 */
public class ShoppingCartFrame extends javax.swing.JInternalFrame implements ShoppingCartEventListener{

    private ShoppingCart shoppingCart = new ShoppingCart();
    private Set<ShoppingCartFrameEventListener> listeners = new HashSet<ShoppingCartFrameEventListener>(); 
    
    private SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss:SS");
    
    /** Creates new form ShoppingCartFrame */
    public ShoppingCartFrame(int x, int y) {
        this.setLocation(x, y);
        initComponents();
        shoppingCart.addShoppingCartFrameListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtProductList = new javax.swing.JTextArea();
        btnCheckout = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setTitle("Shopping Cart");

        txtProductList.setColumns(20);
        txtProductList.setRows(5);
        jScrollPane1.setViewportView(txtProductList);

        btnCheckout.setText("Checkout");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckout)
                    .addComponent(btnClear))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCheckout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        this.txtProductList.setText("");
        for (ShoppingCartFrameEventListener shoppingCartFrameEventListener : listeners) {
            shoppingCartFrameEventListener.shoppingCartClear();
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        for (ShoppingCartFrameEventListener shoppingCartFrameEventListener : listeners) {
            shoppingCartFrameEventListener.shoppingCartCheckout();
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnClear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtProductList;
    // End of variables declaration//GEN-END:variables

    public ShoppingCart getShoppingCart() {
        return shoppingCart;
    }

    
    public void addShoppingCartFrameListener(ShoppingCartFrameEventListener element) {
        listeners.add(element);
    }

    
    public void productAdded(Product product) {
        String label = sdf.format(new Date())+" - "+product.getCategory()+ "\n";
        this.txtProductList.insert(label, 0);
        this.txtProductList.setCaretPosition(0);
    }

    public void cleared() {
        this.txtProductList.setText("");
    }
    
    
}
