package com.wordpress.salaboy.content.headers;

import com.wordpress.salaboy.content.model.*;
import com.wordpress.salaboy.content.model.components.*;
import com.wordpress.salaboy.content.model.meta.*;

import com.wordpress.salaboy.httpheadersoo.*;

global java.util.List results;


rule "add visitor"
    when
        not(RankVisitor())
    then
        insert(new RankVisitor(new Visitor()));

end

rule "banner when language is english"
    when
        $rank: RankVisitor()
        $header: HttpHeader(language matches ".*en.*")
        
    then
        $rank.increaseRank(5); //+5 points for English Users
        
end


rule "TextBox for Mozilla Users!"
    when
        $rank: RankVisitor()
        $header: HttpHeader(userAgent matches ".*Mozilla.*")
    then
        $rank.increaseRank(10); //+10 points for Open Source Users
end


rule "Late visitor"
    when
        $rank: RankVisitor()
        $header: HttpHeader(date matches "")
        
    then
        $rank.decreaseRank(10); //-10 points for Late Visitors doesn't buy
        
end

rule "Google referers"
    when
        $rank: RankVisitor()
        $header: HttpHeader(referer matches ".*google.*")
        
    then

        $rank.increaseRank(3); //3 points for google referals
end

rule "Buy Phone Boost!"
    when
        $rank: RankVisitor()
        $header: HttpHeader(referer matches ".*buy.*phone.*")
        
    then
        $rank.increaseRank(20); //20 points for search parameter Buy Phone!
end